// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJB6G9lYc8-Ez3FWs05BDBxMj1SItWVuw',
    appId: '1:825852190492:web:d0203bb10d52bd0b28a4d9',
    messagingSenderId: '825852190492',
    projectId: 'motimate-eca55',
    authDomain: 'motimate-eca55.firebaseapp.com',
    storageBucket: 'motimate-eca55.firebasestorage.app',
    measurementId: 'G-QZ7RE7S2V8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD64iC7vhW5BZSP4QjDwuSyVJx276SI7Rw',
    appId: '1:825852190492:android:85371c5a803fe74e28a4d9',
    messagingSenderId: '825852190492',
    projectId: 'motimate-eca55',
    storageBucket: 'motimate-eca55.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_OQ3XP6c-r9EbaWQ9E3pTeg2yM5Sdv28',
    appId: '1:825852190492:ios:c2306d2cacf518ba28a4d9',
    messagingSenderId: '825852190492',
    projectId: 'motimate-eca55',
    storageBucket: 'motimate-eca55.firebasestorage.app',
    iosBundleId: 'com.example.motimate',
  );
}
